-- Week04 Lab04
-- LAB | SQL Joins
USE sakila;

-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- List the number of films per category.
SELECT cat.name AS category, COUNT(fc.category_id) AS count FROM sakila.category AS cat
JOIN sakila.film_category AS fc
ON cat.category_id = fc.category_id
GROUP BY cat.name;

-- Retrieve the store ID, city, and country for each store.
SELECT st.store_id AS store, ad.address AS address, ci.city AS city, co.country AS country 
FROM sakila.store AS st
JOIN sakila.address AS ad
ON st.address_id = ad.address_id
JOIN sakila.city AS ci
ON ad.city_id = ci.city_id
JOIN sakila.country AS co
ON ci.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT st.store_id AS store, SUM(pa.amount) AS revenue 
FROM sakila.store AS st
JOIN sakila.customer AS cu
ON st.store_id = cu.store_id
JOIN sakila.payment AS pa
ON cu.customer_id = pa.customer_id
GROUP BY st.store_id;

-- Determine the average running time of films for each category.
SELECT ca.name AS category, AVG(fi.length) AS average_length  
FROM sakila.film AS fi
JOIN sakila.film_category AS fc
ON fi.film_id = fc.film_id
JOIN sakila.category AS ca
ON fc.category_id = ca.category_id
GROUP BY ca.name;
